# Generated by Django 5.1.6 on 2025-04-11 03:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.CharField(max_length=10, null=True)),
                ('bus_line', models.CharField(max_length=3, null=True)),
                ('bus_stop', models.CharField(max_length=10, null=True)),
                ('passenger_density', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], verbose_name='Passenger Density')),
                ('comment', models.CharField(max_length=255, verbose_name='Obstacle Type')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ObstacleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Obstacle Type')),
            ],
        ),
        migrations.CreateModel(
            name='StationLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(max_length=10, verbose_name='Building Code')),
                ('name', models.CharField(max_length=255, verbose_name='Location Name')),
                ('name_eng', models.CharField(default='', max_length=255, verbose_name='Location Name English')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='ObstaclePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('obstacle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.obstacletype', verbose_name='Obstacle Type')),
            ],
        ),
        migrations.CreateModel(
            name='LineThreeRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(unique=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stationlocation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LineSpecialRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(unique=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stationlocation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LineOneRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(unique=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stationlocation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LineFiveRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(unique=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stationlocation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
