# Generated by Django 5.1.6 on 2025-03-09 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObstacleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Obstacle Type')),
            ],
        ),
        migrations.CreateModel(
            name='ObstaclePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('obstacle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.obstacletype', verbose_name='Obstacle Type')),
            ],
        ),
    ]
