# Generated by Django 5.1.6 on 2025-03-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='bus_station',
        ),
        migrations.AddField(
            model_name='feedback',
            name='bus_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='bus_line',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
