# Generated by Django 5.1.6 on 2025-03-31 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_feedback_bus_station_feedback_bus_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='bus_stop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.stationlocation'),
        ),
    ]
