# Generated by Django 5.1.7 on 2025-04-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_feedback_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='bus_id',
            field=models.CharField(null=True),
        ),
    ]
